export { default as Footer } from './Footer'
export { default as GitHubCorner } from './GitHubCorner'
export { default as QuizBackground } from './QuizBackground'
export { default as QuizLogo } from './QuizLogo'
export { default as Widget } from './Widget'